export { LoginPage } from './login';
export { PaymentPage } from './payment';
export { ProductsPage } from './products';
export { AdminPage } from './admin';
export { HomePage } from './home';
export { AccountPage } from './account';
export { MatchesPage } from './matches';
export { SettingsPage } from './settings';
export { PairProgramming } from './pair-program';
